@echo off
echo Iniciando Chrome con Remote Debugging en puerto 9222...
start chrome --remote-debugging-port=9222 --user-data-dir="%TEMP%\chrome-devtools-mcp-profile"
echo Esperando 3 segundos para que Chrome inicie...
timeout /t 3 /nobreak >nul
echo Conectando MCP DevTools...
npx chrome-devtools-mcp@latest --browserUrl http://127.0.0.1:9222
